#!/bin/bash
# Skript lisab kasutajad failist

if [ "$#" -ne 1 ]; then
  echo "Kasutamine: $0 <failinimi>"
  exit 1
fi

fail=$1

while IFS= read -r kasutaja; do
  ./lisa_kasutaja "$kasutaja"
done < "$fail"

