#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
  echo "Ainult root saab skripti käivitada."
  exit 1
fi

if [ -z "$1" ]; then
  echo "Usage: $0 <failinimi>"
  exit 1
fi

logifail="kasutajad_paroolidega.log"

while IFS= read -r kasutaja; do
  parool=$(pwgen 8 1)
  ./lisa_kasutaja "$kasutaja"
  echo "$kasutaja:$parool" | sudo chpasswd
  echo "$kasutaja:$parool" >> "$logifail"
done < "$1"

