#!/bin/bash

#script kutsub ühe faili ja  teeb kasutaja ja parooli


if [ -z "$1" ]; then
  echo "Usage: $0 <failinimi>"
  exit 1
fi

while IFS=: read -r kasutaja parool; do
  ./lisa_kasutaja "$kasutaja"
  echo "$kasutaja:$parool" | sudo chpasswd
done < "$1"

