#!/bin/bash

#skript lisab kasutaja

if [ -z "$1" ]; then
  echo "Usage: $0 <kasutajanimi>"
  exit 1
fi

sudo useradd -m $1

if [ $? -eq 0 ]; then
  echo "Kasutaja $1 loodud."
else
  echo "Kasutaja loomine ebaõnnestus."
fi

