#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage: $0 <kasutajad_fail> <paroolid_fail>"
  exit 1
fi

paste -d: "$1" "$2" | while IFS=: read -r kasutaja parool; do
  ./lisa_kasutaja "$kasutaja"
  echo "$kasutaja:$parool" | sudo chpasswd
done

